import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:heroicons/heroicons.dart';
import 'package:intl_phone_number_input/intl_phone_number_input.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';
import 'package:test_app/common_input.dart';
import 'package:test_app/phonecode.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _inputController = TextEditingController();
  final _inputControllerSearch = TextEditingController();
  PhoneNumber? number;
  late Future<Autogenerated> futureAlbum;
  MaVungs? _mavung;
  List<MaVungs> _mavunglist = [];

  _cc() async {
    var phoneNumber = "+234 500 500 5005";
    number = await PhoneNumber.getRegionInfoFromPhoneNumber(phoneNumber);
  }

  String _error = "";
  bool _isEnable = false;

  Future<Autogenerated> fetchAlbum() async {
    final response =
        await http.get(Uri.parse('http://testlc.app365.vn/api/ma-vung/dau-so'));

    if (response.statusCode == 200) {
      // If the server did return a 200 OK response,
      // then parse the JSON.
      return Autogenerated.fromJson(jsonDecode(response.body));
    } else {
      // If the server did not return a 200 OK response,
      // then throw an exception.
      throw Exception('Failed to load album');
    }
  }

  List<String> _input = [];

  @override
  void initState() {
    futureAlbum = fetchAlbum();
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return GestureDetector(
      onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
      child: Scaffold(
          appBar: AppBar(
            elevation: 0,
            backgroundColor: Colors.white,
            // Here we take the value from the MyHomePage object that was created by
            // the App.build method, and use it to set our appbar title.
          ),
          bottomNavigationBar: Container(
            margin: const EdgeInsets.only(left: 32, right: 32, bottom: 40),
            padding: EdgeInsets.all(16),
            width: MediaQuery.of(context).size.width,
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(4),
                color: _isEnable ? Colors.green : Colors.grey.shade200),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: const [
                Icon(Icons.turn_slight_right_sharp, color: Colors.black),
                Text(
                  "Tiếp tục",
                  style: TextStyle(fontSize: 14, color: Colors.black),
                )
              ],
            ),
          ),
          body: Container(
            color: Colors.white,
            child: Padding(
              padding: const EdgeInsets.all(32.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [Image.asset('assets/images/logo.png')],
                  ),
                  const SizedBox(
                    height: 45,
                  ),
                  Text(
                    'Xin chào!',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                  ),
                  const SizedBox(
                    height: 16,
                  ),
                  Text(
                    'Vui lòng nhập số điện thoại của bạn để quản lý Giao dịch Bất động sản hiệu quả hơn!',
                    style: TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
                  ),
                  const SizedBox(
                    height: 16,
                  ),
                  CommonInput(
                      title: "Số điện thoại ",
                      isEnabledRequire: true,
                      hintText: "Số điện thoại",
                      textInputType: TextInputType.phone,
                      maxLength: 300,
                      onChanged: (value) {
                        if (value.isEmpty) {
                          setState(() {
                            _input.clear();
                          });
                        }
                        _input.add(value);
                        if (value.isNotEmpty &&
                                value[0] == "0" &&
                                value.length != 10 ||
                            value.isNotEmpty &&
                                value[0] != "0" &&
                                value.length != 9) {
                          _error = "Nhập chưa đúng định dạng số điện thoai";
                        } else {
                          _error = "";
                        }
                        _isEnable = _error == "";
                        setState(() {});
                      },
                      prefixWidget: GestureDetector(
                          onTap: () {
                            showMaterialModalBottomSheet(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.only(
                                      topLeft: Radius.circular(40),
                                      topRight: Radius.circular(40)),
                                ),
                                context: context,
                                builder:
                                    (context) => FutureBuilder<Autogenerated>(
                                          future: futureAlbum,
                                          builder: (context, snapshot) {
                                            if (snapshot.hasData) {
                                              final item =
                                                  snapshot.data!.data!.maVungs!;
                                              return StatefulBuilder(
                                                builder: (BuildContext context,
                                                    void Function(
                                                            void Function())
                                                        setStatet) {
                                                  return Container(
                                                    height:
                                                        MediaQuery.of(context)
                                                                .size
                                                                .height *
                                                            0.94,
                                                    decoration: BoxDecoration(
                                                      color: Colors.white,
                                                      borderRadius:
                                                          BorderRadius.only(
                                                              topLeft: Radius
                                                                  .circular(40),
                                                              topRight: Radius
                                                                  .circular(
                                                                      40)),
                                                    ),
                                                    child: Column(
                                                      children: [
                                                        Container(
                                                          child: Row(
                                                            mainAxisAlignment:
                                                                MainAxisAlignment
                                                                    .spaceBetween,
                                                            children: [
                                                              const SizedBox(),
                                                              const Text(
                                                                'Mã vùng',
                                                                style: TextStyle(
                                                                    fontSize: 18,
                                                                    fontWeight:
                                                                        FontWeight
                                                                            .bold),
                                                              ),
                                                              GestureDetector(
                                                                  onTap: () {
                                                                    Navigator.pop(
                                                                        context);
                                                                  },
                                                                  child:
                                                                      const Icon(
                                                                    Icons.close,
                                                                    size: 30,
                                                                    color: Colors
                                                                        .black,
                                                                  ))
                                                            ],
                                                          ),
 padding: EdgeInsets.symmetric(horizontal: 26,vertical: 10),
                                                          decoration: BoxDecoration(
                                                            color: Color(0xfff7f7f7),
                                                            borderRadius:
                                                            BorderRadius.only(
                                                                topLeft: Radius
                                                                    .circular(40),
                                                                topRight: Radius
                                                                    .circular(
                                                                    40)),
                                                          ),
                                                        ),
                                                        const SizedBox(
                                                          height: 10,
                                                        ),
                                                        Expanded(
                                                          child: Container(
                                                            padding:
                                                            const EdgeInsets.only(
                                                                top: 10,
                                                                left: 16,
                                                                right: 16),
                                                            child: Column(
                                                              children: [

                                                                CommonInput(
                                                                  bgrColor: true,
                                                                  prefixWidget:
                                                                  Padding(
                                                                    padding: const EdgeInsets.only(left: 17.0,right: 17),
                                                                    child: Transform.scale(
                                                                      scale: 2,
                                                                      child: const Icon(
                                                                        Icons.search,color: Color(0xff616b79),size: 14,),
                                                                    ),
                                                                  ),
                                                                  hintText: "Tìm kiếm",
                                                                  controller:
                                                                  _inputControllerSearch,
                                                                  onChanged: (value) {
                                                                    _mavunglist.clear();
                                                                    if (value.isEmpty) {
                                                                      setStatet(() {});
                                                                      return;
                                                                    }
                                                                    for (var element
                                                                    in item) {
                                                                      if (element
                                                                          .tenVung!
                                                                          .toLowerCase()
                                                                          .contains(
                                                                          value
                                                                              .toLowerCase()) ||
                                                                          element.code!
                                                                              .toLowerCase()
                                                                              .contains(
                                                                              value
                                                                                  .toLowerCase())) {
                                                                        setStatet(() {
                                                                          _mavunglist.add(
                                                                              element);
                                                                        });
                                                                      }
                                                                    }
                                                                  },
                                                                ),
                                                                const SizedBox(height: 8,),
                                                                _mavunglist.isEmpty
                                                                    ? Expanded(
                                                                  child: ListView
                                                                      .separated(
                                                                    padding: EdgeInsets.zero,
                                                                    itemCount: snapshot
                                                                        .data
                                                                        ?.data
                                                                        ?.maVungs
                                                                        ?.length ??
                                                                        0,
                                                                    itemBuilder:
                                                                        (context,
                                                                        index) {
                                                                      return GestureDetector(
                                                                        onTap:
                                                                            () {
                                                                          setState(
                                                                                  () {
                                                                                _mavung = snapshot
                                                                                    .data!
                                                                                    .data!
                                                                                    .maVungs![index];
                                                                                Navigator.pop(
                                                                                    context);
                                                                              });
                                                                        },
                                                                        child:
                                                                        Container(
                                                                          color: Colors
                                                                              .white,
                                                                          child:
                                                                          Padding(
                                                                            padding:
                                                                            const EdgeInsets.only(left: 16,top: 24.0,bottom: 24),
                                                                            child:
                                                                            Row(
                                                                              mainAxisAlignment:
                                                                              MainAxisAlignment.spaceBetween,
                                                                              children: [
                                                                                Row(
                                                                                  children: [
                                                                                    Image.network(
                                                                                      snapshot.data?.data?.maVungs?[index].icon ?? "",
                                                                                      width: 20,
                                                                                      height: 20,
                                                                                    ),
                                                                                    const SizedBox(
                                                                                      width: 12,
                                                                                    ),
                                                                                    Text('${snapshot.data?.data?.maVungs?[index].ma ?? ""}',style: TextStyle(fontSize: 18),)
                                                                                  ],
                                                                                ),
                                                                                Text(
                                                                                  snapshot.data?.data?.maVungs?[index].tenVung ?? ""
                                                                                  ,style: TextStyle(fontSize: 18),),

                                                                              ],
                                                                            ),
                                                                          ),
                                                                        ),
                                                                      );
                                                                    },
                                                                    separatorBuilder:
                                                                        (BuildContext
                                                                    context,
                                                                        int index) {
                                                                      return Divider(
                                                                        height: 1,
                                                                        color: Color(0xffebebeb),
                                                                        thickness:
                                                                        1,
                                                                      );
                                                                    },
                                                                  ),
                                                                )
                                                                    : Expanded(
                                                                  child: ListView
                                                                      .separated(
                                                                    itemCount:
                                                                    _mavunglist
                                                                        .length ??
                                                                        0,
                                                                    itemBuilder:
                                                                        (context,
                                                                        index) {
                                                                      return GestureDetector(
                                                                        onTap:
                                                                            () {
                                                                          setState(
                                                                                  () {
                                                                                _mavung =
                                                                                _mavunglist[index];
                                                                                Navigator.pop(
                                                                                    context);
                                                                              });
                                                                        },
                                                                        child:
                                                                        Container(
                                                                          color: Colors
                                                                              .white,
                                                                          child:
                                                                          Padding(
                                                                            padding:
                                                                            const EdgeInsets.only(left: 16,top: 24.0,bottom: 24),
                                                                            child:
                                                                            Row(
                                                                              mainAxisAlignment:
                                                                              MainAxisAlignment.spaceBetween,
                                                                              children: [
                                                                                Row(
                                                                                  children: [
                                                                                    Image.network(
                                                                                      _mavunglist[index].icon ?? "",
                                                                                      width: 20,
                                                                                      height: 20,
                                                                                    ),
                                                                                    const SizedBox(
                                                                                      width: 12,
                                                                                    ),
                                                                                    Text('${_mavunglist[index].ma ?? ""}',style: TextStyle(fontSize: 18),)
                                                                                  ],
                                                                                ),
                                                                                Text(_mavunglist[index].tenVung ?? "",style: TextStyle(fontSize: 18),)
                                                                              ],
                                                                            ),
                                                                          ),
                                                                        ),
                                                                      );
                                                                    },
                                                                    separatorBuilder:
                                                                        (BuildContext
                                                                    context,
                                                                        int index) {
                                                                      return Divider(
                                                                        height: 1,color: Color(0xffebebeb),
                                                                        thickness:
                                                                        1,
                                                                      );
                                                                    },
                                                                  ),
                                                                )
                                                              ],
                                                            ),
                                                          ),
                                                        )
                                                      ],
                                                    ),
                                                  );
                                                },
                                              );
                                            } else if (snapshot.hasError) {
                                              return Text('${snapshot.error}');
                                            }

                                            // By default, show a loading spinner.
                                            return const CircularProgressIndicator();
                                          },
                                        ));
                          },
                          child: Container(
                            padding: EdgeInsets.symmetric(
                                horizontal: 12, vertical: 10),
                            color: Colors.transparent,
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Image.network(
                                    _mavung?.icon ??
                                        "http://testlc.app365.vn/files/flags/flag-vietnam.png",
                                    width: 20,
                                    height: 20),
                                const SizedBox(
                                  width: 8,
                                ),
                                Text(
                                  "+${_mavung?.code ?? 84}",
                                  style: TextStyle(
                                      fontSize: 14,
                                      color: Color(0xff616b79
                                      )),
                                ),
                                const SizedBox(
                                  width: 8,
                                ),
                                Icon(
                                  Icons.keyboard_arrow_down_rounded,
                                  color: Color(0xff616b79)
                                )
                              ],
                            ),
                          )),
                      controller: _inputController),
                  Visibility(
                      visible: _error != "",
                      child: Text(
                        _error,
                        style: TextStyle(
                            color: Colors.red,
                            fontSize: 14,
                            fontWeight: FontWeight.w400),
                      ))
                ],
              ),
            ),
          )),
    );
  }
}
