class Autogenerated {
  int? status;
  Data? data;
  String? msg;

  Autogenerated({this.status, this.data, this.msg});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    msg = json['msg'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['msg'] = this.msg;
    return data;
  }
}

class Data {
  int? soDongDaHienThi;
  List<MaVungs>? maVungs;

  Data({this.soDongDaHienThi, this.maVungs});

  Data.fromJson(Map<String, dynamic> json) {
    soDongDaHienThi = json['soDongDaHienThi'];
    if (json['maVungs'] != null) {
      maVungs = <MaVungs>[];
      json['maVungs'].forEach((v) {
        maVungs!.add(new MaVungs.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['soDongDaHienThi'] = this.soDongDaHienThi;
    if (this.maVungs != null) {
      data['maVungs'] = this.maVungs!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MaVungs {
  int? id;
  String? ma;
  String? tenVung;
  String? code;
  String? icon;

  MaVungs({this.id, this.ma, this.tenVung, this.code, this.icon});

  MaVungs.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    ma = json['ma'];
    tenVung = json['tenVung'];
    code = json['code'];
    icon = json['icon'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['ma'] = this.ma;
    data['tenVung'] = this.tenVung;
    data['code'] = this.code;
    data['icon'] = this.icon;
    return data;
  }
}


